version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    links:
      - postgres:postgres_db

  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: bdrinks
      POSTGRES_PASSWORD: Flamingo4
